### ISSUE TITLE
Markdown Feature

### ISSUE THREAD

**Issue by LuigiZaccagnini** [drew5494/the-great-site-generator#10]
Hi Drew5494!

## Feature
I am interested in your project and I would like to add support for Markdown (.md files) in it.

## Example
If users inputs a text file, nothing will change. If a Markdown file is used as input, only the header one syntax feature will be converted into HTML.

If you would like this feature please assign me this issue and reply to let me know. Thanks!

**Comment by drew5494** [comment]
> Hi Drew5494!
> 
> ## Feature
> I am interested in your project and I would like to add support for Markdown (.md files) in it.
> 
> ## Example
> If users inputs a text file, nothing will change. If a Markdown file is used as input, only the header one syntax feature will be converted into HTML.
> 
> If you would like this feature please assign me this issue and reply to let me know. Thanks!

Sounds good
