### ISSUE TITLE
Input Flag Does not work with Directories

### ISSUE THREAD

**Issue by LuigiZaccagnini** [drew5494/the-great-site-generator#3]
## Why Do We Need This?
It would make working with large amount of files a lot easier. 

## What does this enhancement include?
* If the input is a folder, the tool should scan the entire folder looking for text files and output them in the dist folder.

**Comment by drew5494** [comment]
Should work with updated folder support bc28da3cb0dd91f979e2cec44f2ad15f5364ccfe
