### ISSUE TITLE
Don't work with paths as strings

### ISSUE THREAD

**Issue by humphd** [drew5494/the-great-site-generator#5]
It's dangerous to work with filenames and paths as though they are strings, and make assumptions about how they will be constructed.  Especially as you move between operating systems and filesystems, the standards change.

For example, in https://github.com/drew5494/the-great-site-generator/blob/main/thegreatsitegenerator/main.cpp#L59 you assume the path separator.  A better approach is to use something like https://en.cppreference.com/w/cpp/filesystem/path to extract path components and/or put them together.

**Comment by humphd** [comment]
Similar issue with https://github.com/drew5494/the-great-site-generator/blob/main/thegreatsitegenerator/main.cpp#L39.  Use https://en.cppreference.com/w/cpp/filesystem/path/extension

**Comment by drew5494** [comment]
Now using std::filesystem instead of strings 58bda65eaceb4e93f59bc4b0a8715f2fdef1fb4c
