### ISSUE TITLE
Don't hard-code version number

### ISSUE THREAD

**Issue by humphd** [drew5494/the-great-site-generator#7]
In https://github.com/drew5494/the-great-site-generator/blob/main/thegreatsitegenerator/main.cpp#L20 the version number is hard-coded.  This isn't ideal, since it will change with every release.  A better way is to include it in an external header file as a `#define` or the like, see https://stackoverflow.com/questions/27395120/correct-way-to-encode-embed-version-number-in-program-code for tips.

**Comment by drew5494** [comment]
Add CMake versioning 46202fb0ff5edfeb5cdc3d8d90986702995f4dea
