### ISSUE TITLE
Cross-platform build

### ISSUE THREAD

**Issue by humphd** [drew5494/the-great-site-generator#9]
Working with C++ is a great way to target multiple operating systems and platforms.  Doing so requires you to have a build system that works across various systems.  Currently there is no build system, and you give a manual command to compile the code.

A better solution is to use something like [CMake](https://cmake.org/cmake/help/latest/guide/tutorial/index.html#guide:CMake%20Tutorial) or the like.  This can be [integrated with Visual Studio](https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-160) and other IDEs later on.

**Comment by drew5494** [comment]
> Working with C++ is a great way to target multiple operating systems and platforms. Doing so requires you to have a build system that works across various systems. Currently there is no build system, and you give a manual command to compile the code.
> 
> A better solution is to use something like [CMake](https://cmake.org/cmake/help/latest/guide/tutorial/index.html#guide:CMake%20Tutorial) or the like. This can be [integrated with Visual Studio](https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-160) and other IDEs later on.

Thank you.  Will look into this.

**Comment by drew5494** [comment]
Added CMake support https://github.com/drew5494/the-great-site-generator/commit/a79509ccfad4045d96534ab5230d8d966e0b9f56

**Comment by humphd** [comment]
Nice! 👍
